jwt:
  key: test

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

    flyway:
      # user: remote
      # password: MYwmfrlwk01!
      enabled: false
      baseline-on-migrate: true
  flyway:
    location: classpath:db/h2

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    database: h2
    generate-ddl: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: bd6982fbee0ad288fbd7e08f24c2c843
            scope:
              - profile_nickname
              - account_email
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379


---
spring:
  config:
    activate:
      on-profile: local

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

frontend:
  url: http://localhost:5173
backend:
  url: http://localhost:8080



---
spring:
  config:
    activate:
      on-profile: dev

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://southoftheriver.synology.me:8082/login/oauth2/code/kakao

frontend:
  url: http://101.101.209.245
backend:
  url: http://localhost:8082

---
spring:
  config:
    activate:
      on-profile: prod

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: 115.85.181.165:8080/login/oauth2/code/kakao

frontend:
  url: http://101.101.209.245
backend:
  url: http://localhost:8080

---
spring:
  config:
    activate:
      on-profile: test
